### ISSUE TITLE
Handling of obsolete function and subroutine names

### ISSUE THREAD

**Issue by ronsquibbs** [ThemosTsikas/XenakisFreeStochasticMusicFortran#1]
In XenFSM_1.f it appears that, rather than replace obsolete function and subroutine names in the original code, the approach taken is to define functions and subroutines after END so as to preserve the original names in the code above. I have seen examples of function and subroutine definitions placed above the main program: does placing them below have the same effect? (Sorry, this may be a naive question, but I'm trying to make sure I'm following the logic behind the revisions.)

**Comment by ThemosTsikas** [comment]
Correct, it does not matter. Any order of program units is acceptable and equivalent. The code has no modern Fortran features that would enable checking of calls (we might add that).
